analyzer:
  exclude:
    - "lib/backup_old_files/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Avoid print
    - avoid_print
    # Prefer const with constant constructors
    - prefer_const_constructors
    # Prefer const literals to create immutables
    - prefer_const_literals_to_create_immutables
    # Use super parameters
    - use_super_parameters
    # Prefer final fields
    - prefer_final_fields

# Stronger enforcement for our main code
strong-mode:
  implicit-casts: false
  implicit-dynamic: false
