[build]
  publish = "build/web"
  command = "flutter build web --release --no-tree-shake-icons"

[build.environment]
  NODE_VERSION = "18"

# Clear all caches for this deployment
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Force service worker update
[[headers]]
  for = "/flutter_service_worker.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Cache for icons
[[headers]]
  for = "/favicon.*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Long cache for assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
